version: "3.1"
services:
  mariadb:
    image: mariadb:10.1
    container_name: blog-mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data_blog:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel_blog
      - MYSQL_USER=laravel_blog_user
      - MYSQL_PASSWORD=laravel_blog_password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: blog-phpmyadmin
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - '81:80'
    volumes:
      - phpmyadmin_data_blog:/home/docker
    environment:
      PMA_HOST: mariadb
volumes:
  mariadb_data_blog:
    driver: local
  phpmyadmin_data_blog:
    driver: local